---
- hosts: archivesspace
  # become: yes
  # become_method: sudo
  # become_user: root
  # remote_user: root
  gather_facts: yes
  roles:
    - role: geerlingguy.java
      become: yes
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: archivesspace
